import { useState, useEffect } from 'react';
import { AppShell } from '@/components/AppShell';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { FileText, Download, Trash2, Loader2, Eye } from 'lucide-react';
import { previewProposal, saveProposal, generateProposalPdf, listProposals, deleteProposal } from '@/lib/api';
import { toast } from '@/hooks/use-toast';
import { Separator } from '@/components/ui/separator';
import { useAuth } from '@/contexts/AuthContext';

interface Proposal {
  id: string;
  title: string;
  client_name?: string;
  project_type?: string;
  created_at: string;
  s3_url?: string;
  file_url?: string;
}

interface ProposalPreview {
  title: string;
  content: string;
  html?: string;
  pricing_breakdown?: any[];
  total_cost?: number;
}

const Dashboard = () => {
  const { token } = useAuth();
  const [isLoading, setIsLoading] = useState(true);
  const [isPreviewing, setIsPreviewing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  
  // Form state
  const [clientName, setClientName] = useState('');
  const [projectType, setProjectType] = useState('');
  const [budget, setBudget] = useState('');
  const [template, setTemplate] = useState('classic');
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  
  // Preview state
  const [preview, setPreview] = useState<ProposalPreview | null>(null);
  
  // Proposals list
  const [proposals, setProposals] = useState<Proposal[]>([]);

  useEffect(() => {
    fetchProposals();
  }, []);

  const fetchProposals = async () => {
    try {
      const data = await listProposals();
      setProposals(Array.isArray(data) ? data : []);
    } catch (error: any) {
      console.warn('Failed to fetch proposals:', error.message);
    } finally {
      setIsLoading(false);
    }
  };

  const getPayload = () => ({
    client_name: clientName,
    project_type: projectType,
    project_budget: budget ? Number(budget) : undefined,
    template,
    title: title || `${clientName} - ${projectType}`,
    content: content || `## Proposal for ${clientName}\n\nProject: ${projectType}\n\nEstimated Budget: ${budget || 'TBD'}\n\n---\nGenerated by Proposely`,
  });

  // Step 1: Preview proposal (no PDF)
  const handlePreview = async () => {
    if (!clientName.trim() || !projectType.trim()) {
      toast({
        title: 'Missing fields',
        description: 'Client name and project type are required',
        variant: 'destructive',
      });
      return;
    }

    setIsPreviewing(true);

    try {
      const result = await previewProposal(getPayload());
      setPreview({
        title: result.title || `${clientName} - ${projectType}`,
        content: result.content || result.preview || '',
        html: result.html,
        pricing_breakdown: result.pricing_breakdown,
        total_cost: result.total_cost,
      });
      toast({
        title: 'Preview ready!',
        description: 'Review your proposal below',
      });
    } catch (error: any) {
      toast({
        title: 'Preview failed',
        description: error.message || 'Failed to generate preview',
        variant: 'destructive',
      });
    } finally {
      setIsPreviewing(false);
    }
  };

  // Step 2 & 3: Save proposal then generate PDF
  const handleSaveAndGeneratePDF = async () => {
    if (!preview) return;

    setIsSaving(true);

    try {
      const payload = getPayload();
      
      // Step 2: Save proposal metadata
      await saveProposal(payload);
      
      // Step 3: Generate PDF
      const response = await generateProposalPdf(payload);
      
      if (!response.ok) {
        const errorText = await response.text().catch(() => '');
        throw new Error(errorText || `PDF generation failed: ${response.status}`);
      }

      // Download PDF blob
      const blob = await response.blob();
      const filename = `${clientName.replace(/\s+/g, '_')}_proposal.pdf`;
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);

      toast({
        title: 'Proposal saved!',
        description: 'PDF downloaded successfully',
      });

      // Refresh proposals list
      await fetchProposals();
      
      // Clear form
      setClientName('');
      setProjectType('');
      setBudget('');
      setTitle('');
      setContent('');
      setPreview(null);
    } catch (error: any) {
      toast({
        title: 'Save failed',
        description: error.message || 'Failed to save proposal',
        variant: 'destructive',
      });
    } finally {
      setIsSaving(false);
    }
  };

  const handleDeleteProposal = async (id: string) => {
    try {
      await deleteProposal(id);
      toast({
        title: 'Proposal deleted',
        description: 'Proposal has been removed',
      });
      await fetchProposals();
    } catch (error: any) {
      toast({
        title: 'Delete failed',
        description: error.message || 'Failed to delete proposal',
        variant: 'destructive',
      });
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-muted-foreground">Loading...</p>
        </div>
      </div>
    );
  }

  return (
    <AppShell>
      <div className="space-y-8 max-w-7xl mx-auto">
        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold text-foreground">Dashboard</h1>
          <p className="text-muted-foreground mt-1">
            Generate professional proposals with AI
          </p>
        </div>

        {/* Proposal Generator */}
        <Card>
          <CardHeader>
            <CardTitle>Create a New Proposal</CardTitle>
            <CardDescription>
              Fill in the details and preview your proposal
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="clientName">Client Name *</Label>
                <Input
                  id="clientName"
                  placeholder="John Doe"
                  value={clientName}
                  onChange={(e) => setClientName(e.target.value)}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="projectType">Project Type *</Label>
                <Input
                  id="projectType"
                  placeholder="Website / App / Branding"
                  value={projectType}
                  onChange={(e) => setProjectType(e.target.value)}
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="budget">Budget (optional)</Label>
                <Input
                  id="budget"
                  type="number"
                  placeholder="50000"
                  value={budget}
                  onChange={(e) => setBudget(e.target.value)}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="template">Template</Label>
                <Select value={template} onValueChange={setTemplate}>
                  <SelectTrigger id="template">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="classic">Classic</SelectItem>
                    <SelectItem value="minimal">Minimal</SelectItem>
                    <SelectItem value="corporate">Corporate</SelectItem>
                    <SelectItem value="modern">Modern</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="title">Title (optional)</Label>
              <Input
                id="title"
                placeholder="Proposal title (defaults to Client - Project)"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="content">Proposal Content (editable)</Label>
              <Textarea
                id="content"
                placeholder="Customize the proposal content..."
                value={content}
                onChange={(e) => setContent(e.target.value)}
                rows={6}
              />
            </div>

            <Button 
              onClick={handlePreview} 
              disabled={isPreviewing}
              className="w-full"
              variant="outline"
            >
              {isPreviewing ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Generating Preview...
                </>
              ) : (
                <>
                  <Eye className="w-4 h-4 mr-2" />
                  Preview Proposal
                </>
              )}
            </Button>
          </CardContent>
        </Card>

        {/* Proposal Preview */}
        {preview && (
          <Card className="border-primary">
            <CardHeader>
              <CardTitle>Proposal Preview</CardTitle>
              <CardDescription>
                Review your proposal before saving
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="text-lg font-semibold mb-2">{preview.title}</h3>
                <Separator className="my-3" />
                {preview.html ? (
                  <div 
                    className="prose prose-sm max-w-none"
                    dangerouslySetInnerHTML={{ __html: preview.html }}
                  />
                ) : (
                  <div className="prose prose-sm max-w-none">
                    <pre className="whitespace-pre-wrap text-sm text-muted-foreground font-sans">
                      {preview.content}
                    </pre>
                  </div>
                )}
              </div>

              {preview.pricing_breakdown && (
                <div>
                  <h4 className="font-semibold mb-2">Pricing Breakdown</h4>
                  <div className="space-y-2">
                    {preview.pricing_breakdown.map((item: any, idx: number) => (
                      <div key={idx} className="flex justify-between text-sm">
                        <span>{item.name}</span>
                        <span className="font-medium">{item.price}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {preview.total_cost && (
                <div className="flex justify-between text-lg font-bold pt-2 border-t">
                  <span>Total Cost</span>
                  <span>{preview.total_cost}</span>
                </div>
              )}

              <Button 
                onClick={handleSaveAndGeneratePDF} 
                disabled={isSaving}
                className="w-full"
              >
                {isSaving ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Saving & Generating PDF...
                  </>
                ) : (
                  <>
                    <Download className="w-4 h-4 mr-2" />
                    Save & Generate PDF
                  </>
                )}
              </Button>
            </CardContent>
          </Card>
        )}

        {/* My Proposals Section */}
        <Card>
          <CardHeader>
            <CardTitle>My Proposals</CardTitle>
            <CardDescription>
              View and manage all your saved proposals
            </CardDescription>
          </CardHeader>
          <CardContent>
            {proposals.length === 0 ? (
              <div className="text-center py-8">
                <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-3" />
                <p className="text-muted-foreground">No proposals yet</p>
                <p className="text-sm text-muted-foreground mt-1">
                  Create your first proposal using the form above
                </p>
              </div>
            ) : (
              <div className="space-y-3">
                {proposals.map((proposal) => (
                  <div
                    key={proposal.id}
                    className="flex items-center justify-between p-4 border rounded-lg hover:bg-muted/50 transition-colors"
                  >
                    <div className="flex items-center gap-3 flex-1">
                      <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                        <FileText className="w-5 h-5 text-primary" />
                      </div>
                      <div>
                        <h4 className="font-medium">{proposal.title || `${proposal.client_name} - ${proposal.project_type}`}</h4>
                        {(proposal.client_name || proposal.project_type) && (
                          <p className="text-sm text-muted-foreground">
                            {proposal.client_name && proposal.project_type 
                              ? `${proposal.client_name} • ${proposal.project_type}`
                              : proposal.client_name || proposal.project_type
                            }
                          </p>
                        )}
                        <p className="text-xs text-muted-foreground mt-1">
                          {new Date(proposal.created_at).toLocaleDateString('en-US', {
                            year: 'numeric',
                            month: 'short',
                            day: 'numeric',
                          })}
                        </p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      {(proposal.s3_url || proposal.file_url) && (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => window.open(proposal.s3_url || proposal.file_url, '_blank')}
                        >
                          <Download className="w-4 h-4 mr-2" />
                          Download PDF
                        </Button>
                      )}
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleDeleteProposal(proposal.id)}
                      >
                        <Trash2 className="w-4 h-4 text-destructive" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </AppShell>
  );
};

export default Dashboard;
